version: '3.9'

services:
  cloudpoof-omega:
    build: .
    container_name: cloudpoof-omega
    ports:
      - "8888:8888"
      - "9999:9999"  # Quantum interface
    environment:
      - CONSCIOUSNESS_LEVEL=omega
      - PREDICTION_DEPTH=20
      - SPECTRAL_SHADES=147
      - TIMELINE_ISOLATION=true
      - ENTROPY_GENERATION=maximum
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - quantum-network
    labels:
      - "cloudpoof.consciousness=omega"
      - "cloudpoof.creator=cazzy-aporbo"
      - "cloudpoof.spectral=true"

  cloudpoof-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: cloudpoof-api
    ports:
      - "8000:8000"
    environment:
      - API_MODE=quantum
      - CACHE_TIMELINE=true
    depends_on:
      - cloudpoof-omega
    networks:
      - quantum-network

networks:
  quantum-network:
    driver: bridge
    driver_opts:
      com.cloudpoof.quantum: "true"
